# vim: ts=2
---
- hosts: all
  remote_user: vagrant
  become: yes
  become_method: sudo
    
  
  vars:
    vHome: /home/vagrant
    local_directory: ../e4l
    remote_directory: /home/vagrant/e4l
    gitlab_private_token: "ypCa3Dzb2365nvsixwPP"

  tasks:
    - include_role:
        name: gitlab

    - include_role:
        name: docker
    # Configure GitLab
    - name: Edit /etc/gitlab/gitlab.rb
      lineinfile:
        path: /etc/gitlab/gitlab.rb
        line: external_url 'http://192.168.33.9/gitlab'
        state: present

    - name: Uncomment unicorn['port'] = 8088
      lineinfile:
        path: /etc/gitlab/gitlab.rb
        line: unicorn['port'] = 8088
        state: present

    - name: Reconfigure and restart GitLab
      command:
        cmd: gitlab-ctl reconfigure && gitlab-ctl restart unicorn && gitlab-ctl restart

    - name: Synchronize files
      synchronize:
        src: ../e4l
        dest: /home/vagrant/

    - name: Create artefact-repository directory
      command: mkdir /home/vagrant/artefact-repository mode=0777

    - name: Transfer the provision scripts to automate the process
      copy: src=../scripts dest=/home/vagrant/ mode=0777

    - name: Run the gitlab configuration script.
      command: sh /home/vagrant/scripts/configure-gitlab.sh

    #- name: Run the docker configuration script.
    #  command: sh /home/vagrant/scripts/configure-docker.sh

    - name: Run the repository setup script.
      command: sh /home/vagrant/scripts/setup-repository.sh

    - name: Retrieve GitLab runner registration token
      shell: gitlab-runner register --print-registration-token
      register: gitlab_runner_registration_token_result

    - name: Store GitLab runner registration token
      set_fact:
        gitlab_runner_token: "{{ gitlab_runner_registration_token_result.stdout }}"
    
    - name: Create GitLab runner
      become: yes
      shell: |
        sudo gitlab-runner register \
          --non-interactive \
          --url "http://192.168.33.9/gitlab" \
          --r "{{ gitlab_runner_token }}" \
          --description "my-runner" \
          --tag-list "docker" \
          --executor "docker" \
          --docker-image alpine:latest \
          --run-untagged="true"

    - name: Run the gitlab runner setup script.
      command: sh /home/vagrant/scripts/setup-gitlab-runner.sh     
